//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample_mvc5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studentmark
    {
        public int Student_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime Student_Dob { get; set; }
        public int Age { get; set; }
        public string Favorite_Subject { get; set; }
        public string Interested_Course { get; set; }
        public int Maths_Mark { get; set; }
        public int Chemistry_Mark { get; set; }
        public int Comp_Mark { get; set; }
        public bool Is_Deleted { get; set; }
        public System.DateTime Created_Time_Stamp { get; set; }
        public System.DateTime Updated_Time_Stamp { get; set; }
        public string Username { get; set; }
        public int Password { get; set; }
    }
}
